version: '3.9'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_lab_data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - lab-obs
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./conf/prometheus/:/etc/prometheus/
      - prometheus_data:/var/lib/prometheus
    ports:
      - 9090:9090
    networks:
      - lab-obs

networks:
  lab-obs:
    driver: bridge


volumes:
  grafana_lab_data:
  prometheus_data:
    
    
    
   