global:
  scrape_interval: "2s"
  scrape_timeout: "5s"
  evaluation_interval: "1m"
scrape_configs:
  - job_name: 'poc-app-metrics'
    metrics_path: /metrics
    static_configs:
      - targets:
          - "docker.for.mac.host.internal:8080"
  - job_name: 'fake-braum'
    metrics_path: /metrics
    static_configs:
      - targets:
          - "docker.for.mac.host.internal:3001" 
        